name: islamic_app
description: A simple Islamic prayer app with Qibla and Azan.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  audioplayers: ^5.2.1
  flutter_compass: ^0.8.0
  geolocator: ^10.1.0
  shared_preferences: ^2.2.2
  vibration: ^3.1.6
  http: ^1.6.0
  connectivity_plus: ^7.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/azaan.mp3
